# ProGuard/R8 rules for Guangzhou Bus Ticketing

# Keep application classes (adjust package as needed)
-keep class com.guangzhou.busticketing.** { *; }

# Keep Firebase messaging
-keep class com.google.firebase.messaging.** { *; }
-keep class com.google.firebase.iid.** { *; }

# Keep Retrofit and Gson models
-keep class retrofit2.** { *; }
-keep class com.squareup.okhttp3.** { *; }
-keep class com.google.gson.** { *; }

# Keep annotations used by libraries
-keepattributes *Annotation*

# Keep model classes used by reflection (you may need to add packages used by serialization)
#-keep class com.yourpackage.models.** { *; }

# Keep Parcelable/Serializable implementations generated by Kotlin or libraries
-keepclassmembers class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator CREATOR;
}

# Keep OkHttp internal classes used by reflection
-dontwarn okhttp3.**
-dontwarn okio.**

# Keep generated GSON type adapters (if any) - adjust as necessary
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Uncomment and adapt any additional rules required by 3rd-party libraries you use
